enum TransitionType {
  LEFT_TO_RIGHT,
  RIGHT_TO_LEFT,
  TOP_TO_BOTTOM,
  BOTTOM_TO_TOP,
  CENTER_LR_IN,
  CENTER_TB_IN,
  CENTER_LR_OUT,
  CENTER_TB_OUT,
  LEFT_TOP_ROUNDER,
  LEFT_CENTER_ROUNDER,
  LEFT_BOTTOM_ROUNDER,
  RIGHT_BOTTOM_ROUNDER,
  RIGHT_TOP_ROUNDER,
  RIGHT_CENTER_ROUNDER,
  TOP_CENTER_ROUNDER,
  BOTTOM_CENTER_ROUNDER,
  CENTER_ROUNDER,
}

enum StripTransitionType {
  LEFT_TO_RIGHT,
  RIGHT_TO_LEFT,
  TOP_TO_BOTTOM,
  BOTTOM_TO_TOP
}

enum AnimatedOn { onTap, onHover }
